include ${TOPDIR}/Makefile.vars

${WEB}/%.html: %.php ${INCLUDE}
	@if [ ! -d ${WEB} ]; then mkdir -p ${WEB}; fi
	php -d include_path="${TOPDIR}" -f $< > phpout
	@grep -q "</html>" phpout && cp phpout $@ && rm phpout || (echo "Error occurred during production of $@: check phpout for errors"; exit 1)
